module.exports = {
    account_detail: "account_detail",
    accounts: "accounts",
    apis: "apis",
    ids: "ids",
    constraints: "constraints",
    default_value: "default_value",
    fields: "fields",
    modify_history: "modify_history",
    project_partner: "project_partner",
    project_status: "project_status",
    project_user: "project_user",
    projects: "projects",
    tables: "tables",
    task_member: "task_member",
    task_modify: "task_modify",
    task_status: "task_status",
    tasks: "tasks",
    versions: "versions",
}
